name: hello-world
on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"